# Generated by Django 4.2.7 on 2023-11-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technologie', 'verbose_name_plural': 'Technologies'},
        ),
    ]
