# Generated by Django 4.2.7 on 2023-11-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0003_project_title_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='openclassrooms.project'),
            preserve_default=False,
        ),
    ]
