# Generated by Django 4.2.7 on 2023-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0005_remove_skill_project_remove_technology_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
