# Generated by Django 4.2.7 on 2023-11-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0011_alter_project_skill_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_github',
            field=models.URLField(blank=True),
        ),
    ]
