# Generated by Django 4.2.7 on 2023-11-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0002_alter_technology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
