# Generated by Django 4.2.7 on 2023-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0007_project_url_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
