# Generated by Django 4.2.7 on 2023-11-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0008_project_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_url',
            new_name='image_path',
        ),
    ]
