# Generated by Django 4.2.7 on 2023-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0009_rename_image_url_project_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
