# Generated by Django 4.2.7 on 2023-11-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclassrooms', '0012_alter_project_url_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
